services:
  db:
    image: postgres:16
    container_name: weblogros_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: weblogros
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    container_name: weblogros_backend
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/weblogros
      JWT_SECRET: clave_secreta_muy_larga_y_aleatoria_weblogros_2026
    depends_on:
      - db

  frontend:
    build: ./apps/frontend
    container_name: weblogros_frontend
    environment:
      BACKEND_URL: http://backend:3001
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: weblogros_nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend


volumes:
  postgres_data:
