import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 📚 ROOT LAYOUT: envuelve TODAS las páginas del App Router. Aquí va el <html>/<body> y lo
//    común a todo el sitio (el Header). "children" es cada página que se renderiza dentro.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 📚 Header fuera de {children} → aparece en todas las páginas sin repetirlo. */}
        <Header />
        {children}
      </body>
    </html>
  );
}
