"use client"
import Link from "next/link"
import { FormEvent, use, useState } from "react"
import { useRouter } from "next/navigation"
import { apiFetch, ApiError } from "@/lib/api"
import { Button } from "@/app/components/ui/Button"
import { ErrorMessage } from "@/app/components/ui/Error"
import { Input } from "@/app/components/ui/Input"
export default function NuevoLogroPage({ params }: { params: Promise<{slug:string}> }) { const {slug}=use(params); const router=useRouter(); const [nombre,setNombre]=useState(""); const [puntos,setPuntos]=useState(""); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); async function submit(e:FormEvent){e.preventDefault();const clean=nombre.trim();const value=Number(puntos);if(!clean)return setError("Escribe un nombre para el logro.");if(!Number.isInteger(value)||value<0)return setError("Los puntos deben ser un entero mayor o igual que 0.");setError("");setSaving(true);try{await apiFetch(`/api/equipos/${encodeURIComponent(slug)}/logros`,{method:"POST",auth:true,body:JSON.stringify({nombre:clean,puntos:value})});router.push(`/equipos/${slug}/logros`)}catch(cause){setError(cause instanceof ApiError&&cause.status===401?"Tu sesión ha caducado. Inicia sesión para crear logros.":cause instanceof ApiError&&cause.status===403?"Solo un administrador de este equipo puede crear logros.":cause instanceof Error?cause.message:"No se pudo crear el logro.")}finally{setSaving(false)}} return <div className="mx-auto max-w-2xl space-y-6 px-5 py-10"><Link className="font-mono text-xs uppercase tracking-widest text-coral" href={`/equipos/${slug}/logros`}>← Volver al catálogo</Link><div><p className="font-mono text-xs uppercase tracking-[.18em] text-coral">Nuevo logro</p><h1 className="mt-2 font-display text-4xl font-bold">Crear logro</h1><p className="mt-2 text-ink-soft">Define el nombre y los puntos que tendrá dentro del catálogo.</p></div><form onSubmit={submit} className="space-y-6 rounded-3xl border border-paper-deep bg-white/70 p-6 sm:p-8">{error&&<ErrorMessage>{error}</ErrorMessage>}<Input label="Nombre del logro" name="nombre" value={nombre} onChange={e=>setNombre(e.target.value)} placeholder="Ej. Primer sprint completado" required maxLength={120}/><Input label="Puntos" name="puntos" type="number" min="0" step="1" value={puntos} onChange={e=>setPuntos(e.target.value)} placeholder="10" required/><Button type="submit" disabled={saving}>{saving?"Guardando…":"Crear logro"}</Button></form></div> }
